name: ym_speech_to_text
description: A Flutter plugin that exposes device specific speech to text recognition capability.
version: 0.0.2
homepage: https://github.com/yashmanghnani/ym_speech_to_text

environment:
  sdk: ">=3.4.0 <4.0.0"      
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_platform_interface: ^2.3.0
  json_annotation: ^4.9.0
  clock: ^1.1.2
  pedantic: ^1.11.1
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.16.0
  web: ^1.1.1
  speech_to_text_windows: ^1.0.0+beta.8
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  fake_async: ^1.3.2
  mockito: ^5.4.6
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.csdcorp.speech_to_text
        pluginClass: SpeechToTextPlugin
      ios:
        pluginClass: SpeechToTextPlugin
        sharedDarwinSource: true
      web:
        pluginClass: SpeechToTextPlugin
        fileName: speech_to_text_web.dart
      macos:
        pluginClass: SpeechToTextPlugin
        sharedDarwinSource: true
      windows: 
        default_package: speech_to_text_windows
